### ISSUE TITLE
Regarding to MeshCommander UI

### ISSUE THREAD

**Issue by tedlee0502** [Ylianst/MeshCommander#2]
Hello Ylianst,  
Sorry about to bother you. 
We are Atrust Computer from Taiwan, and now developing a project that using MeshCommander open source to reproduce a remote device system management. 
If possible, I would like to know your comments for the UI design to move MeshCommander to top right side of page as below screen capture. 
Thank you.  
![AMC1](https://user-images.githubusercontent.com/62271120/77995144-d15e6a80-735d-11ea-9c86-d6fb6581788c.jpg)
![AMC2](https://user-images.githubusercontent.com/62271120/77995148-d28f9780-735d-11ea-9e4e-26e5af808a26.jpg)
![AMC3](https://user-images.githubusercontent.com/62271120/77995149-d3282e00-735d-11ea-917f-d7bdd2611607.jpg)
![AMC4](https://user-images.githubusercontent.com/62271120/77995151-d4595b00-735d-11ea-9b47-8d4f657460a3.jpg)

**Comment by Ylianst** [comment]
Hi. Sorry for the delay. This looks like really interesting improvements! I like all the extra information you are getting from your agent. Since MeshCommander is open source, your not required to put the "MeshCommander" name in your application, I would remove it completely.

So maybe just "Console for Atrust AMT-capable models v1.6.1". No need to put "MeshCommander", you can use your own name.

Also, if I may, I would use the "logoback.png" to put your company logo, like below (just an example):

![atrust](https://user-images.githubusercontent.com/1319013/78143982-da921a80-73e3-11ea-9294-c06c92a81a26.png)

Personally, I would put the console version number on the computer selection screen and the Atrust agent version in the "System Status" tab as a new line under the "Intel ME". So you would have:

```
Intel(R) ME         v11.8.70 activated in Admin Control Mode (ACM)
Software Agent      Atrust system agent for Intel AMT v1.0.4
```

This way you would not have anything on the top right. Of course, that is just my preference.

Let me know if I answered your question. You are free to change the name of the tool to what you like, no need to reference back to the open source project. Hope that helps.

**Comment by Ylianst** [comment]
FYI. This is the logoback.png I used for the screens above with the white gradiant, feel free to use it as a starting point.

![logoback](https://user-images.githubusercontent.com/1319013/78147380-44acbe80-73e8-11ea-9037-aea59be861dc.png)

**Comment by tedlee0502** [comment]
Thanks for providing valuable suggestions. Finally we decided to continue to use the name of "**Atrust MeshCommander**".
